[build]
  command = "pip install --upgrade pip && pip install -r requirements.txt && python app.py"
  publish = "/public"  # if you're generating static files, change accordingly

[[plugins]]
  package = "@netlify/plugin-python"
