[build]
  command = "pip install --upgrade pip && pip install -r requirements.txt && python app.py"
  publish = "public"  # Adjust based on your app's output directory

[[plugins]]
  package = "@netlify/plugin-python"
